### ISSUE TITLE
Quality of Life and Compatibility Improvements

### ISSUE THREAD

**Issue by Foxy6670** [gaucho-matrero/altoclef#237]
# Quality of Life: 
## Auto Mend (for big mining projects)
When a pickaxe in the inventory is low on durability and has mending, the bot should (with a non-silk pickaxe) mine ores that are easily accessible, common, and give off a bit of XP. If it's a silk touch pickaxe, it should do other things, such as kill animals/mobs with the pickaxe in the offhand.

# Compatibility:
## legitMine and strip mine support
Due to some servers having anti-Xray, the bot can get very confused. As it appears now, legitMine does not effect alto clef, and it still tries to X-ray. And \#tunnel is already a Baritone command, so strip mining shouldn't be too hard to add.
### Discord username (if you want updates)
`Foxo, the Funtime Fox#3402`
### Developer Notes (leave this blank)

_Difficulty_: **_Extreme_**
_Estimated Time Required_: **_3-6 months_**
Once development starts.

**Comment by JamesGreen31** [comment]
Edit: Scaled the project. 

The reason this will be hard is because of the way Altoclef works. Currently, pretty much everything it does is via xray, so if it cannot xray it cannot see. While we could create a strip mine task (still hard because of limiting its vision), it would only appear to be mining legit. It would infact still be using xray. 

Even if the plug-in doesn't break altoclefs ability to see, there is no guarantee that it will stay that way, so this is effectively impossible to maintain as any change to the plug-in means a re-write of altoclef. 

If we wanted to have a permanent solution, we would need to write a system where the bot is able to gather information based on blocks that are visible to the player. There are some techniques available for this, but it still would be extremely time consuming to implement. 

This isba cool idea, but we are probably at least 2 years away from that level of integration. Of course, that could change if an altoclef superstar came on the scenes, but given the current status of the project, this is extremely distant.
