### ISSUE TITLE
Bot gets stuck on Nether Roof

### ISSUE THREAD

**Issue by JustaSqu1d** [gaucho-matrero/altoclef#275]
## Steps to Reproduce (as best as you can)
Open a staircase to the nether roof (via glitches or whatever).

## Expected Behavior
Bot goes up to the nether roof and comes back down or just doesn't go there in the first place.

## Actual Behavior (What lead to the bot getting permanently stuck)
The bot doesn't find the way down the nether roof.

## Crashlogs and Screenshots (if applicable)
_(you may drag + drop text logs and images here, thanks GitHub)_

### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by JamesGreen31** [comment]
This is actually kind of anticipated by design. The bot avoids attempting to break bedrock as its...well unbreakable.

If stuck on the nether roof, the bot *should* search for an opening, but it won't reasonably find one as 99% of the roof is unpassable.

If you had the bot somehow walk up there, it should get back down. But if the both was tp'ed up there, it will definitely get stuck.

**Comment by JustaSqu1d** [comment]
The nether entrance portal was close to the staircase leading up to the nether roof. I searched for ancient debris and this ended with the bot stuck on the nether roof as it continues in the direction of the ancient debris. Then it couldn't find where it came down from. I think it would be great if the bot just didn't get to the nether roof in the first place.

**Comment by TomIsFat** [comment]
The same happens when I run "@get cobbled_deepslate 1000", sometimes bot keeps digging for deepslates in -48,  sometimes it gets stuck in the bedrock.

**Comment by JustaSqu1d** [comment]
This isn't an altoclef, it's a baritone one.
